### ISSUE TITLE
"Undefined index: version"

### ISSUE THREAD

**Issue by jeremycherfas** [OleVik/grav-plugin-twigfeeds#11]
Error in 3.1.1

On line 105 of `utilities.php`

**Comment by OleVik** [comment]
Using what configuration?

**Comment by jeremycherfas** [comment]
Configuration of what? Everything else -- Grav, admin etc, is completely up to date.

**Comment by OleVik** [comment]
The plugin, ie `/user/config/plugins/twigfeeds.yaml`.

**Comment by jeremycherfas** [comment]
````
enabled: true
cache: true
static_cache: true
debug: true
twig_feeds:
  -
    source: 'https://stream.jeremycherfas.net/content/all?_t=rss'
    name: Stream
    start: 0
    end: 10

````

**Comment by OleVik** [comment]
Using your settings with v3.1.1, I get no error from `Utilities.php`. Did this occur when updating from v3.0.4 or v3.1.0-rc.1? The line in question is a part of the `getVersion()`-method, used in cache-busting between minor and major versions. What is the full error that PHP logged?

**Comment by jeremycherfas** [comment]
Very strange. In my local development copy, when I enable twigfeeds, I get the error originally reported. Here is more context.

````
/Applications/MAMP/htdocs/grav-blog/user/plugins/twigfeeds/Utilities.php
            }
        }
    }
 
    /**
     * Fetch the plugin version from the blueprints or manifest
     * @param array $path Path to file
     * @param array $mode 'blueprint' or 'manifest'
     * @return string Retrieved version
     */
    public function getVersion($path, $mode = 'blueprint')
    {
        if ($mode == 'blueprint') {
            $blueprint = file_get_contents($path);
            $data = Yaml::parse($blueprint);
            return $data['version'];
        } elseif ($mode == 'manifest') {
            $manifest = file_get_contents($path);
            $json = json_decode($manifest, true);
            return $json['config']['version'];
        }
    }
 
    /**
     * Compares two semantic versions
     * @param string $old Old version, in SemVer format
     * @param string $new New version, in SemVer format
     * @return array Comparative version information
     */
    function compareSemVer($old, $new)
    {
        $versions = array();
        $versions['old']['version'] = $old;
        $versions['new']['version'] = $new;
 
        $old = SemVerParser::parse($old);
        $versions['old']['major'] = $old->getMajor();
        $versions['old']['minor'] = $old->getMinor();
        $versions['old']['patch'] = $old->getPatch();
        if ($old->hasPreRelease()) {
Arguments
"Undefined index: version"
````

In the live production copy, the error is different.

````
Server Error
Sorry, something went terribly wrong!

0 - "" is not a valid SemVer"
````
This is whaT I FIND IN THE LOGS
````
[2017-04-17 23:28:15] grav.CRITICAL: "" is not a valid SemVer" - Trace: #0 /home/jcgrav/jeremycherfas.net/user/plugins/twigfeeds/vendor/naneau/semver/src/Naneau/SemVer/Parser.php(43): Naneau\SemVer\Regex::matchSemVer(NULL) #1 /home/jcgrav/jeremycherfas.net/user/plugins/twigfeeds/Utilities.php(121): Naneau\SemVer\Parser::parse(NULL) #2 /home/jcgrav/jeremycherfas.net/user/plugins/twigfeeds/twigfeeds.php(152): TwigFeeds\Utilities->compareSemVer(NULL, '3.1.1') #3 [internal function]: Grav\Plugin\TwigFeedsPlugin->outputFeeds(Object(RocketTheme\Toolbox\Event\Event), 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /home/jcgrav/jeremycherfas.net/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /home/jcgrav/jeremycherfas.net/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/jcgrav/jeremycherfas.net/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(277): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onTwigSiteVaria...', NULL) #8 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Twig/Twig.php(321): Grav\Common\Grav->fireEvent('onTwigSiteVaria...') #9 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite('php') #10 /home/jcgrav/jeremycherfas.net/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #11 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Processors/RenderProcessor.php(18): Pimple\Container->offsetGet('output') #12 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\RenderProcessor->process() #13 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() #14 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #15 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) #16 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) #17 /home/jcgrav/jeremycherfas.net/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #18 /home/jcgrav/jeremycherfas.net/index.php(52): Grav\Common\Grav->process() #19 {main} [] []
````

**Comment by OleVik** [comment]
I am suspecting a slight regression in updating here, where the `getVersion`-method looks for a version for comparison in the manifest, which might not yet exist. Could you copy the contents of your /user/data/twigfeeds/manifest.json here? Then a `bin/gpm plugin twigfeeds clearcache` should forcibly bust the cache and allow the plugin to set the version as expected.

In fact I can replicate this, and it is due to `version` missing from within `config` in manifest.json. Busting the cache or deleting the manifest will solve it.

**Comment by jeremycherfas** [comment]
Yes, I can confirm that deleting `manifest.json` and then re-enabling the plugin solved the issue locally. This is before updating to grav 1.2.3, which I will do next.

**Comment by OleVik** [comment]
I will assume that the issue is now resolved and the plugin is working.
